markdown: redcarpet
<<<<<<< HEAD
highlighter: pygments
permalink: /:title

url: http://ramakrishnavedantam928.github.io
baseurl:

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed
=======
permalink: /:title

url: http://aigarsdz.github.io
baseurl: /brume

redcarpet:
  extensions: [strikethrough, tables]
>>>>>>> FETCH_HEAD
